#!/usr/bin/env bash

### TPUT things ###
if [[ -t 1 ]]; then
  BO=$(tput bold)
  R=$(tput setaf 1)
  G=$(tput setaf 2)
  B=$(tput setaf 4)
  r=$(tput sgr0)
else
  BO=""
  R=""
  G=""
  B=""
  r=""
fi

### FUNCTIONS ###
show_help() {
  echo "Use: ${B}fzpaper${r} [${G}-f${r}] [${G}-d${r}] <flags>"
  echo ""
  echo "Options:"
  echo "  ${G}-h${r}:       This help message."
  echo "  ${G}-f${r}:       The directory for the wallpapers.conf variables file. (defaults to ~/.config/hypr/themes)"
  echo "  ${G}-d${r}:       The directory of the images. (defaults to ~/Pictures/Wallpapers)"
}

### FLAGS ###
while getopts "hwlf:d:" opt; do
  case $opt in
    h) show_help; exit 0 ;;
    f) V_DIRECTORY="$OPTARG" ;;
    d) I_DIRECTORY="$OPTARG" ;;
    ?) show_help; exit 1 ;;
  esac
done
shift $((OPTIND - 1))

### CONST ###
ERRMES="${R}${BO}error:${r}"
OLD_D=$(pwd)

V_DIRECTORY=${V_DIRECTORY:-"$HOME/.config/hypr/themes"}
I_DIRECTORY=${I_DIRECTORY:-"$HOME/Pictures/Wallpapers"}

# Verification
if [[ ! -d "$V_DIRECTORY" ]]; then
  echo "${ERRMES} the obtained wallpaper.conf variables file directory does not exist."
  exit 1
fi

if [[ ! -d "$I_DIRECTORY" ]]; then
  echo "${ERRMES} the obtained image directory does not exist."
  exit 1
fi

### GETTING THE IMG ###
cd "$I_DIRECTORY" || exit 1
img=$(
  fzf --preview \
    'kitten icat \
      --clear \
      --transfer-mode=memory \
      --unicode-placeholder \
      --stdin=no \
      --place="${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0" \
      {}
    ' \
    --preview-window=right:70% \
    --prompt="Wallpaper > "
  )
cd "$OLD_D" || exit 1

if [[ -z "$img" || ! -e "$I_DIRECTORY/$img" ]]; then
  echo "${ERRMES} the obtained image is empty or does not exist."
  exit 1
fi

### SET ###
rm "$V_DIRECTORY/wallpapers.conf"
echo "\$MAIN_WALLPAPER = $I_DIRECTORY/$img" >> "$V_DIRECTORY/wallpapers.conf"
echo "\$LOCK_WALLPAPER = $I_DIRECTORY/$img" >> "$V_DIRECTORY/wallpapers.conf"
hyprctl hyprpaper wallpaper ",$I_DIRECTORY/$img"
